- README.md
- cypress/e2e/logs-page.cy.ts
- src/components/logs-query-input.css
- src/components/logs-table.css
- src/components/logs-table.tsx
- src/components/logs-toolbar.css
- src/components/logs-toolbar.tsx
- src/components/spacer.tsx
- src/components/tenant-dropdown.tsx
- src/components/toggle-play.css
- src/hooks/useLogs.ts
- src/loki-client.ts
- src/pages/logs-detail-page.tsx
- src/pages/logs-page.tsx
- src/test-ids.ts
Extract toolbar component to add tenant dropdown
> Add tenant dropdown

- src/components/logs-query-input.tsx
Fixes: https://issues.redhat.com/browse/LOG-2877
> Disable run button when the query is empty

- cypress/integration/logs-page.cy.ts
- src/components/refresh-interval-dropdown.tsx
- src/components/time-range-dropdown.tsx
- src/hooks/useLocalStorage.tsx
- src/pages/logs-page.tsx
Fixes: https://issues.redhat.com/browse/LOG-2882
https://user-images.githubusercontent.com/5461414/183030798-0bff99c5-1ad1-4a5d-bdbd-e9e595e48d9a.mov
> Preserve time configuration

- src/components/logs-table.tsx
Fixes: https://issues.redhat.com/browse/LOG-2876
> Fix resource link for containers

- src/pages/logs-detail-page.tsx
- src/pages/logs-page.tsx
Use `{ log_type =~ ".+" } | json` as default query to enrich UI by displaying severity by default
> use better default query parsing json

- src/hooks/useLogs.ts
Fixes: https://issues.redhat.com/browse/OU-55
> Avoid updating time when histogram re renders

- cypress/integration/logs-detail-page.cy.ts
- cypress/integration/logs-page.cy.ts
- src/components/logs-toolbar.tsx
- src/components/refresh-interval-dropdown.tsx
- src/components/tenant-dropdown.tsx
- src/components/time-range-dropdown.tsx
- src/components/toggle-play.tsx
- src/pages/logs-detail-page.tsx
- src/pages/logs-page.tsx
- src/test-ids.ts
Fixes: https://issues.redhat.com/browse/LOG-2917
> Disable query executors when query is empty

- cypress/integration/logs-detail-page.cy.ts
- cypress/integration/logs-dev-page.cy.ts
- src/__tests__/logql-query.spec.ts
- src/hooks/useLogs.ts
- src/index.tsx
- src/logql-query.ts
- src/loki-client.ts
- src/pages/logs-dev-page.tsx
- src/severity.ts
- src/value-utils.ts
Addresses: https://issues.redhat.com/browse/OU-50
> Add namespace filter

- src/loki-client.ts
- src/severity.ts
Fixes: https://issues.redhat.com/browse/LOG-3062
> Fix unknown severity value filtering

- src/cancellable-fetch.ts
- src/loki-client.ts
Extract cancellable fetch on its own file
> Extract cancellable fetch

- package-lock.json
- package.json
upgrade:
- console dynamic plugin deps to recommended version, 
- fix vulnerable d3 dep
> upgrade console deps

- package.json
- src/components/logs-histogram.tsx
- src/components/logs-query-input.tsx
- src/components/logs-table.tsx
- src/components/logs-toolbar.tsx
- src/components/refresh-interval-dropdown.tsx
- src/components/tenant-dropdown.tsx
- src/hooks/useLocalStorage.tsx
- src/hooks/useLogs.ts
- src/logs.types.ts
- src/loki-client.ts
- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/severity.ts
- tsconfig.json
- webpack.config.ts
> Enable typescript strict mode

- cypress/integration/logs-dev-page.cy.ts
- cypress/integration/logs-page.cy.ts
- src/components/logs-toolbar.tsx
- src/components/toggle-button.css
- src/components/toggle-button.tsx
- src/components/toggle-histogram-button.tsx
- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/pages/logs-page.tsx
- src/test-ids.ts
Fixes: https://issues.redhat.com/browse/LOG-3212
This PR also adds the histogram date controls to the detail view so users can select a time range for specific resource logs
https://user-images.githubusercontent.com/5461414/198305746-061090ed-a29d-4fec-ad8d-1bcae8f0bc1e.mov
> Add histogram toggle and toggle button component

- package-lock.json
Fixes: https://issues.redhat.com/browse/LOG-3335
> Fix loader utils vulnerable dependency

- package-lock.json
- package.json
Fixes: https://issues.redhat.com/browse/LOG-3383
> Upgrade "qs" vulnerable dependency

- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/pages/logs-page.tsx
Fixes: https://issues.redhat.com/browse/LOG-3385
> Execute query only when "run query" button is pressed

- .eslintrc.yml
- src/components/time-range-select-modal.css
- src/components/time-range-select-modal.tsx
- src/hooks/useLogs.ts
- src/value-utils.ts
> Add date range validation

- src/components/logs-table.tsx
- src/hooks/useLogs.ts
- src/hooks/useURLState.ts
- src/logs.types.ts
- src/loki-client.ts
- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/pages/logs-page.tsx
Fixes: https://issues.redhat.com/browse/OU-123
Related case: https://issues.redhat.com/browse/LOG-3322
> Use backend date sorting for consistent table results

- cypress/fixtures/resource-api-fixtures.ts
- cypress/integration/logs-dev-page.cy.ts
- src/attribute-filters.tsx
- src/pages/logs-dev-page.tsx
Fixes: https://issues.redhat.com/browse/LOG-3427
Use namespace scoped api for dev console to avoid setting additional resource listing permissions
> Use namespace scoped api to fetch dev console resources

- cypress/integration/logs-dev-page.cy.ts
- src/components/filters/attribute-value-data.tsx
- src/components/filters/search-select.tsx
Fixes: https://issues.redhat.com/browse/LOG-3427
Adds message when user has no listing permission over resources.
> Handle resource request errors

- package-lock.json
- package.json
Fixes: 
https://issues.redhat.com/browse/LOG-3456
https://issues.redhat.com/browse/LOG-3457
> Upgrade vulnerable json5 and glob-parent dependencies

- console-extensions.json
- package.json
Disable dev console for release-5.5
> Disable dev console

- cypress/integration/logs-dev-page.cy.ts
- src/e2e-tests-app.tsx
- src/index.tsx
- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/value-utils.ts
- webpack.standalone.config.ts
Fixes: https://issues.redhat.com/browse/LOG-3461
This PR adds logic to the dev console view to handle infrastructure tenant logs
> LOG-3461: Fix infrastructure logs request on dev console

- cmd/plugin-backend.go
namespace plugin env vars to avoid collisions with other context variables
> Namespace env vars

- src/components/logs-histogram.tsx
- src/components/precision-time-picker.tsx
> Fix time range validation 

- src/date-utils.ts
> Fix 24 hour time formatting

- src/date-utils.ts
> fix time format using 24 hour time

- web/.eslintrc.yml
- web/src/attribute-filters.tsx
- web/src/components/filters/attribute-value-data.tsx
- web/src/components/logs-table.tsx
- web/src/e2e-tests-app.tsx
- web/src/hooks/useURLState.ts
- web/src/pages/logs-detail-page.tsx
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
This PR adds the `no-shadow` rule and removes the shadowed variables
> Add lint rule to remove shadowed variables

- package.json
- src/__tests__/date-utils.spec.ts
- src/date-utils.ts
- src/value-utils.ts
- webpack.config.ts
Cherry pick from: https://github.com/openshift/logging-view-plugin/pull/69
> Parse date manually as DateTimeFormat is not cross browser consistent

- web/package.json
- web/src/__tests__/date-utils.spec.ts
- web/src/date-utils.ts
- web/src/value-utils.ts
- web/webpack.config.ts
cherry pick from https://github.com/openshift/logging-view-plugin/pull/69
> Fix crossbrowser date format

- web/src/__tests__/logql-query.spec.ts
- web/src/components/logs-query-input.css
- web/src/components/logs-query-input.tsx
- web/src/hooks/useURLState.ts
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
Fixes: https://issues.redhat.com/browse/LOG-3454
This PR will:
- Add an error message when the query is invalid
- When filters are cleared, it will fallback to the default query to avoid displaying errors as before it just cleared the query
https://user-images.githubusercontent.com/5461414/220084468-0eed169b-f3cb-4cb6-b448-8e67bac2d253.mov
> Add error message when the query is invalid

- web/src/__tests__/logql-query.spec.ts
- web/src/components/logs-query-input.css
- web/src/components/logs-query-input.tsx
- web/src/hooks/useURLState.ts
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
Cherry pick from https://github.com/openshift/logging-view-plugin/pull/68
> add invalid query message

- web/cypress/fixtures/query-range-fixtures.ts
- web/cypress/integration/logs-page.cy.ts
- web/src/cancellable-fetch.ts
- web/src/components/error-message.css
- web/src/components/error-message.tsx
- web/src/components/logs-table.css
- web/src/components/logs-table.tsx
https://issues.redhat.com/browse/OU-70
This PR adds UI suggestions on how to fix common errors
> add debug info based on Loki error messages

- web/cypress/fixtures/query-range-fixtures.ts
- web/cypress/integration/logs-page.cy.ts
- web/src/cancellable-fetch.ts
- web/src/components/error-message.css
- web/src/components/error-message.tsx
- web/src/components/logs-table.css
- web/src/components/logs-table.tsx
Manual cherry pick from https://github.com/openshift/logging-view-plugin/pull/77
Fixes: 
https://issues.redhat.com/browse/LOG-2874
https://issues.redhat.com/browse/LOG-3750
> [release-5.6] add debug info based on loki error messages

- web/src/__tests__/value-utils.spec.ts
- web/src/components/error-message.css
- web/src/components/error-message.tsx
- web/src/value-utils.ts
Manual cherry pick from #88 
Fixes: https://issues.redhat.com/browse/LOG-3750
> [release-5.6] add missing permission message and debug suggestion

- web/src/components/logs-table.tsx
- web/src/hooks/useLogs.ts
- web/src/hooks/useURLState.ts
- web/src/logs.types.ts
- web/src/pages/logs-detail-page.tsx
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
> [release-5.6] Make load more logs consistent with the sorting direction

- src/components/logs-table.tsx
- src/hooks/useLogs.ts
- src/hooks/useURLState.ts
- src/logs.types.ts
- src/pages/logs-detail-page.tsx
- src/pages/logs-dev-page.tsx
- src/pages/logs-page.tsx
> [release-5.5] make load more logs consistent with the sorting direction

- web/cypress/integration/logs-dev-page.cy.ts
- web/cypress/integration/logs-page.cy.ts
- web/src/attribute-filters.tsx
- web/src/hooks/useURLState.ts
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
Fixes: https://issues.redhat.com/browse/LOG-3758
> Link log_type with selected tenant

- web/src/pages/logs-detail-page.tsx
Fixes: 
https://issues.redhat.com/browse/LOG-3218
https://issues.redhat.com/browse/LOG-4051
> Fix log detail view resource toggle and histogram date selection

- src/pages/logs-detail-page.tsx
Fixes: 
https://issues.redhat.com/browse/LOG-4051
https://issues.redhat.com/browse/LOG-3218
> [release-5.5] Fix logs detail page resource toggle and histogram date range selection

- pkg/server/manifest_handler.go
- pkg/server/server.go
- pkg/server/server_test.go
- pkg/server/testdata/index.html
- pkg/server/testdata/plugin-entry.js
> [release-5.6] disable cache for plugin entry files

- web/src/hooks/useLogs.ts
- web/src/loki-client.ts
manual cherry pick for: [#109](https://github.com/openshift/logging-view-plugin/pull/109)
related issue: [OU-189](https://issues.redhat.com/browse/OU-189)
> [release-5.6] Show Query button is in "Streaming logs" status.

- README.md
- config/alerts-charts.patch.json
- config/dev-alerts.patch.json
- pkg/server/manifest_handler.go
- web/console-extensions.json
- web/src/getAlertingRules.ts
- web/src/getPlatformAlertingRules.ts
- web/src/getUserAlertingRules.ts
- web/src/logs.types.ts
- web/src/loki-client.ts
This PR adds support for log based alerts in the dev console by using alerting rules filtering
Jira: https://issues.redhat.com/browse/OU-105
> Add dev console log based alerts

- web/src/pages/logs-detail-page.tsx
- web/src/pages/logs-dev-page.tsx
This PR allows the detail page view to select a time range using the histogram
> LOG-4305: Fix time range selection from histogram

- web/package-lock.json
> LOG-4323: Upgrade semver vulnerable dependendency

- web/i18next-parser.config.js
- web/src/i18n.ts
To make it easier to see how the i18n setup differs between our plugins.
> Sort i18n config to make it easier to diff against other plugins

- web/scripts/start-console.sh
Update `start-console.sh` to check the cluster endpoint in `env.list` against the current cluster endpoint.
> Check previous vs. current cluster endpoint for creation of env vars

- web/src/hooks/useURLState.ts
Allows user to share URLs with pre-filled filters correctly
> LOG-4439: Initialize filters from url

- OWNERS
> OU-239: Add all team members to all repo's OWNERS 

- package-lock.json
- package.json
Fixes eslint and tough-cookie vulnerable dependencies
> LOG-4584: Fix vulnerable dependencies

- .dockerignore
- .gitignore
- Dockerfile
- Dockerfile.ci
- go.mod
- go.sum
update images to ubi9, golang version and golang.org/x/net
Manual cherry pick of #144
> LOG-4667: Fix http2 rapid reset upgrading golang.org/x/net

- web/src/hooks/useLogActionsExtension.tsx
- web/src/korrel8r.types.ts
Fixes the alert details page's "See related logs" link to work with the breaking changes in korrel8r v0.5.0.
> Updates for korrel8r v0.5.0

- web/package-lock.json
- web/package.json
Upgrade follow-redirects parent dependencies to upgrade to a safe version
> LOG-4924: Upgrade follow-redirects parent dependencies

- web/cypress/integration/logs-dev-page.cy.ts
- web/locales/en/plugin__logging-view-plugin.json
- web/package-lock.json
- web/package.json
- web/src/attribute-filters.tsx
- web/src/components/logs-query-input.tsx
- web/src/components/logs-toolbar.tsx
- web/src/hooks/useLogs.ts
- web/src/pages/logs-dev-page.tsx
This PR adds the namespace filter to the dev console logs. This will allow users to select multiple namespaces in a single query, the default namespace selection is based on the dev console dropdown.
https://github.com/openshift/logging-view-plugin/assets/5461414/1f170826-a849-475c-8922-58517f3c215e
> OU-283: allow dev console to add more namespaces to the default selection

- web/src/attribute-filters.tsx
As dev users do not have access to list all namespace in the cluster, the projects api is used to load the namespaces the user has access to
> LOG-5020: use the Openshift projects api for fetching dev console logs namespaces

- .gitignore
- web/cypress/fixtures/resource-api-fixtures.ts
- web/cypress/integration/logs-dev-page.cy.ts
- web/src/attribute-filters.tsx
- web/src/logs.types.ts
- web/src/loki-client.ts
- web/src/pages/logs-detail-page.tsx
- web/src/pages/logs-dev-page.tsx
Use Loki label values API to fetch dropdown values
> LOG-5020: use Loki label values API to fetch dropdown options

- web/cypress/integration/logs-detail-page.cy.ts
- web/cypress/integration/logs-dev-page.cy.ts
- web/cypress/integration/logs-page.cy.ts
- web/src/pages/logs-detail-page.tsx
- web/src/pages/logs-dev-page.tsx
- web/src/pages/logs-page.tsx
This PR disables and hides the histogram when results are metrics
> LOG-5048: disable histogram when query results are metrics

- web/package-lock.json
- web/package.json
Upgrades follow-redirect vulnerable dependency
> LOG-5249: fix follow redirect vulnerable dependency

- web/package-lock.json
- web/package.json
- web/src/__tests__/logql-query.spec.ts
- web/src/logql-query.ts
Manual cherry pick of #200 for release-5.6
> [release-5.6] LOG-5761: Manual cherry pick line filters

- Dockerfile.konflux
This PR adds a new Dockerfile specific for Konflux builds
> OU-506: add konflux dockerfile

- scripts/image.sh
> NO-JIRA Update image.sh
