Dockerfile
README.md
cypress/e2e/logs-page.cy.ts
logging-view-plugin-resources.yml
mockModules/dummy.tsx
scripts/image.sh
src/hooks/useLogs.ts
src/index.tsx
src/logs.types.ts
src/loki-client.ts
src/pages/logs-page.tsx

Allow the plugin to read a ConfigMap that holds configuration on how to fetch data from loki, the default configuration is to use the LokiStack.

Add support for ConfigMap to choose connection between Loki or LokiStack

---

src/components/logs-histogram.tsx

Fixes: https://issues.redhat.com/browse/LOG-2875
Fixes: https://issues.redhat.com/browse/OU-54

Fix empty histogram tooltip when a single severity is selected

---

cypress/integration/logs-detail-page.cy.ts
src/components/logs-toolbar.tsx
src/hooks/useLogs.ts
src/pages/logs-detail-page.tsx
src/test-ids.ts

When selecting severity filter on the detail page the view was not updated until run query was pressed

Fix severity dropdown sync on detail page

---

cypress/integration/logs-detail-page.cy.ts
src/index.tsx
src/pages/logs-detail-page.tsx
src/pages/logs-page.tsx

A tenant will be preselected based on the namespace of the pod. This will allow users to see `infrastructure` logs for pods in `openshift`, `openshift-*`, `kube-*`, `default` namespaces
addresses https://issues.redhat.com/browse/LOG-2992

Preselect tenant based in namespace on detail view

---

src/components/logs-table.tsx

Use the message instead of the whole content to display log rows in the table

Improve table message display

---

src/components/logs-table.tsx
src/value-utils.ts

If the log does not contain k8s resources do not display them

Do not display resources that are empty in the logs table

---

src/pages/logs-dev-page.tsx

Fixes: https://issues.redhat.com/browse/LOG-3424
This PR includes the following adjustments for the dev console logs:
- Update the time range selection on the dropdown when is selected on the histogram
- Disable controls when the query is empty
- Adjust histogram and time range selector horizontal alignment
https://user-images.githubusercontent.com/5461414/207318812-17f3e476-fa4b-4eca-883f-f8d3e7ef112c.mov

update Dropdown time when selecting a range in the histogram

---

cypress/integration/logs-page.cy.ts
src/components/logs-histogram.tsx
src/components/time-range-select-modal.tsx
src/date-utils.ts
src/time-range.ts
src/value-utils.ts

this PR fixes the histogram bars not displaying for sub-second time ranges, also:
- Refactors time formatting centralizing time related functions in `date-utils`
- Disables selecting the same start and end dates when using the mouse to select a range in the histogram

Improve histogram display for sub second time resolution

---

cypress/integration/logs-page.cy.ts
src/components/precision-time-picker.css
src/components/precision-time-picker.tsx
src/components/time-range-select-modal.tsx
src/hooks/useBoolean.ts
src/value-utils.ts

This PR adds a new component that can handle sub-second resolution when selecting a time range.
https://user-images.githubusercontent.com/5461414/213389159-3ec1bf44-1c3c-4fb0-801c-1fb0d740cd2e.mov

Add precision time picker for time range modal

---

web/src/components/logs-histogram.tsx
web/src/components/precision-time-picker.tsx

Fixes: https://issues.redhat.com/browse/LOG-3583
This PR will:
- Fix the validation for the precision time range
- Constrain logs histogram bars width so they are visible on sub second resolutions

Fix time range validation

---

.gitignore
config/alerts.patch.json
web/console-extensions.json
web/cypress/integration/logs-alerts.cy.ts
web/package.json
web/src/__tests__/logql-query.spec.ts
web/src/components/alerts/logs-alerts-metrics.css
web/src/components/alerts/logs-alerts-metrics.tsx
web/src/components/logs-metrics.tsx
web/src/components/tenant-dropdown.tsx
web/src/e2e-tests-app.tsx
web/src/getAlertingRules.ts
web/src/hooks/useRefWidth.ts
web/src/logql-query.ts
web/src/logs.types.ts
web/src/loki-client.ts
web/src/tenants.ts
web/src/test-ids.ts

https://issues.redhat.com/browse/OU-103
https://issues.redhat.com/browse/OU-104
This PR will add:
- Metrics component to display loki based metrics on the alert detail view
- Fetch function to get alerts from loki so console can merge with the current prometheus alerts
- Add `config/alerts.patch.json` to provide the `alerts` feature on allowed OCP versions
https://user-images.githubusercontent.com/5461414/214549412-78c87f65-a1a2-46bd-9946-3b2ef00a047f.mov

Add logs based alerts

---

web/src/date-utils.ts

Fixes: https://issues.redhat.com/browse/LOG-3583
This PR fixes the 24 hour formatting after selecting a range using the time picker

Fix 24 hour time formatting

---

web/src/date-utils.ts

- Removes am and pm from the time format

Fix time format using 24 hour time

---

web/cypress/fixtures/query-range-fixtures.ts
web/cypress/integration/logs-alerts.cy.ts
web/src/components/alerts/logs-alerts-metrics.tsx
web/src/components/logs-metrics.tsx
web/src/date-utils.ts

This PR adds better error handling when log metrics returns empty data, also adds date validation in the case the returned data has invalid values.

Handle empty metrics data in logs

---

src/__tests__/loki-client-spec.ts
src/cancellable-fetch.ts
src/date-utils.ts
src/logs.types.ts
src/loki-client.ts

Fixes: https://issues.redhat.com/browse/LOG-3498
This PR increases the default fetch timeout to `60s` and allows the timeout to be configured using a ConfigMap (timeout value in seconds):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: logging-view-config
namespace: logging-view
labels:
app: logging-view-plugin
app.kubernetes.io/part-of: logging-view-plugin
data:
config: |
{
"timeout": 80
}
```

Fix request timeout

---

web/src/components/logs-query-input.tsx
web/src/hooks/useLogs.ts
web/src/hooks/useURLState.ts

https://issues.redhat.com/browse/LOG-3454
This PR adds better error messages when the query is empty, also it prevents to send an empty query to the backend

Improve error message when the query is empty

---

config/alerts.patch.json
web/console-extensions.json
web/cypress/integration/logs-alerts.cy.ts
web/package.json
web/src/getAlertingRules.ts
web/src/getPlatformAlertingRules.ts
web/src/getUserAlertingRules.ts

This PR will group the `audit` and `infrastructure` tenants into the platform alerts source, and `application` into user alerts source.
https://user-images.githubusercontent.com/5461414/223421482-0e6c10cd-b796-4768-956c-d000bdb7169e.mov
Image for testing: `quay.io/gbernal/logging-view-plugin:alert-sources`

Group alerts based on user or platforms source

---

cypress/fixtures/query-range-fixtures.ts
cypress/integration/logs-page.cy.ts
src/cancellable-fetch.ts
src/components/error-message.css
src/components/error-message.tsx
src/components/logs-table.css
src/components/logs-table.tsx

Manual cherry pick from https://github.com/openshift/logging-view-plugin/pull/77
Address: https://issues.redhat.com/browse/LOG-2874

[release-5.5] Add debug info

---

web/src/__tests__/value-utils.spec.ts
web/src/components/error-message.css
web/src/components/error-message.tsx
web/src/value-utils.ts

Fixes: https://issues.redhat.com/browse/LOG-3750
Improves the message when logs cannot be fetched due to permissions, adds a suggestion on how to solve the issue.

add missing permission message and debug suggestion

---

web/src/components/logs-table.tsx
web/src/hooks/useLogs.ts
web/src/hooks/useURLState.ts
web/src/logs.types.ts
web/src/pages/logs-detail-page.tsx
web/src/pages/logs-dev-page.tsx
web/src/pages/logs-page.tsx

Fixes: https://issues.redhat.com/browse/OU-166
This PR adds the correct sorting `start` and `end` params when loading more logs.

Make load more logs consistent with the sorting direction

---

pkg/server/manifest_handler.go
pkg/server/server.go
pkg/server/server_test.go
pkg/server/testdata/index.html
pkg/server/testdata/plugin-entry.js

Disable caching for plugin entry files to avoid stalled content after upgrading the plugin version

Disable cache for plugin entry files

---

web/src/__tests__/logql-query.spec.ts
web/src/components/logs-query-input.tsx
web/src/hooks/useURLState.ts
web/src/logql-query.ts

This PR fixes:
- Execute query only when a ctrl+enter keyboard command is pressed instead of every character, a query can still be triggered by a change in control components that update the query
- When a value on the logQL expression pipeline or label matcher is not defined, leave the value empty instead of adding `undefined`, keeping the initial query unchanged

Fix query input events and logQL query parsing

---

web/src/hooks/useLogs.ts
web/src/loki-client.ts

**Related Issue** 
https://issues.redhat.com/browse/OU-167
**Overview** 
Updated loki-client so that the websocket remains open for logs streaming. The issue was because of a malformed websocket URL. Also updated the script start-console.sh to remove the existing env file before creating a new one.
**Explanation** 
Logs streaming begins by displaying logs from the past hour. Previously, we set this to `start=3600000` milliseconds (i.e. 1 hour) but the Loki HTTP API docs state this parameter should be in **nanoseconds Unix epoch** (e.g. `start=1685563694`, meaning May 31, 2023, 8:8:14PM GMT). Because we were not formatting the websocket url correctly we could not stream the logs. 
This PR removes the ‘start’ parameter because the Loki HTTP API already defaults the 'start' parameter to the …

OU-167: Show Query button is in "Streaming logs" status. 

---

web/locales/en/plugin__logging-view-plugin.json
web/src/components/error-message.tsx

This PR adds a message to help the user fix the input size too long error, particularly when a non-admin user has access to too many namespaces

Add error fix suggestion for too long input size

---

.gitignore
hack/docker-compose/docker-compose.test.yml
hack/docker-compose/loki/loki-config.yml
hack/docker-compose/loki/promtail-config.yml
hack/docker-compose/loki/rules/application/test-loki-rule.yml
hack/docker-compose/loki/rules/fake/test-loki-rule.yml
hack/docker-compose/loki/rules/infrastructure/test-loki-rule.yml
hack/docker-compose/proxy.conf
web/README.md

This PR adds some testing files to be able to run Loki with the paths that LokiStack uses to mimic the environment in a cluster

Add docker compose testing files

---

web/cypress/integration/logs-page.cy.ts
web/src/__tests__/attribute-filters.spec.ts
web/src/attribute-filters.tsx

**Related Issue**
https://issues.redhat.com/browse/OCPBUGS-14902
**Summary** 
Fix the content filter by converting text input into a raw string (`<text…>`) instead of plain string ("<text>"). This allows special characters to be escaped within Loki LogQLs.
**Resources**
[https://grafana.com/blog/2021/01/05/how-to-escape-special-characters-with-lokis-logql](https://grafana.com/blog/2021/01/05/how-to-escape-special-characters-with-lokis-logql)
**Before** 
The text input ""manger-role"" causes a parsing error. 
**After**
The text input is now wrapped in backtick (``) instead of quotes (""). The text input `"manger-role"` no longer causes a parsing error.

OCPBUGS-14902: Loki search does not allow special chars

---

web/src/getAlertingRules.ts
web/src/value-utils.ts

Fixes: [LOG-4429](https://issues.redhat.com/browse/LOG-4429) by filtering the tenant based on the namespace

LOG-4429: filter alerting rules tenant based on namespace

---

web/cypress/fixtures/query-range-fixtures.ts
web/cypress/integration/logs-page.cy.ts
web/src/components/logs-table.tsx

Display the content of the log if the log is not a json object, which means is already formatted.
fixes: https://issues.redhat.com/browse/OCPBUGS-11977

LOG-4465: Display correct message if logQL expression has line formatting

---

web/cypress/integration/logs-dev-page.cy.ts
web/locales/en/plugin__logging-view-plugin.json
web/src/components/logs-toolbar.tsx
web/src/hooks/useURLState.ts
web/src/pages/logs-dev-page.tsx
web/src/test-ids.ts

This PR adds a checkbox in the dev perspective logs view that removes the current namespace filter so dev users can search in all namespaces they have access to. 
https://github.com/openshift/logging-view-plugin/assets/5461414/96b115ec-6e2b-4379-ab0b-2831edf076a2

OU-223: add all namespaces check to dev console view

---

web/cypress/integration/logs-dev-page.cy.ts
web/locales/en/plugin__logging-view-plugin.json
web/src/components/logs-toolbar.tsx
web/src/hooks/useURLState.ts
web/src/pages/logs-dev-page.tsx
web/src/test-ids.ts

This reverts commit ae70e27f3a91ba88f6a6e74d45d73abff4363df1.
This feature wont be compatible with the fine-grained logs-access feature in logging 5.8, so an alternative will be created.

Revert "OU-223: add all namespaces check to dev console view"

---

.dockerignore
.gitignore
Dockerfile
Dockerfile.ci
go.mod
go.sum

update images to ubi9, golang version and golang.org/x/net

LOG-4614: fix http2 rapid reset upgrading golang.org/x/net

---

.dockerignore
.gitignore
Dockerfile
Dockerfile.ci
go.mod
go.sum

update images to ubi9, golang version and golang.org/x/net
Manual cherry pick of #144

LOG-4666: Fix http2 rapid reset upgrading golang.org/x/net

---

web/package-lock.json
web/package.json
web/src/components/time-range-select-modal.tsx

This PR address a bug caused by handling different versions of patternfly as the plugin spans on different versions of the console

LOG-4682: fix time picker patternfly dependencies

---

go.mod
go.sum

The dependency was added in the recent CVE mitigation, but this project does not actually make use of it.

Remove unnecessary x/net dependency

---

README.md

The dev console feature `dev-console` present on the console 4.12 was back-ported and landed on 4.11.52. This allows customers to use the dev console without having to upgrade OCP to 4.12

LOG-4504: update compatibility matrix

---

logging-view-plugin-resources.yml
web/src/hooks/useLogActionsExtension.tsx
web/src/korrel8r-client.ts
web/src/korrel8r.types.ts

With this PR, we just use the first korrel8r goal that has some LogQL results. In other words, if the korrel8r API returns multiple LogQL queries that have results, we ignore all but the first one in the API response.
https://github.com/openshift/logging-view-plugin/assets/460802/30a61144-82bc-42b2-adfb-2608065b1e31

OU-199: Use korrel8r to load logs related to an alert

---

web/src/__tests__/attribute-filters.spec.ts
web/src/attribute-filters.tsx

If a matcher value is changed manually into a regex, do not alter the operator so the query results filter as expected by the user

LOG-4810: Do not change operator if selector value is regex

---

Makefile

This is to fix a build error when building with the CI go builder image:
```
$ make build-backend
go build -o plugin-backend cmd/plugin-backend.go
go: inconsistent vendoring in /home/syedriko/go/src/github.com/openshift/logging-view-plugin:
github.com/evanphx/json-patch@v5.6.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
...
```
Here is an example: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/46011/rehearse-46011-pull-ci-openshift-logging-view-plugin-release-5.6-images/1729191600048836608/build-log.txt

Added -mod=readonly to make the CI go builder happy

---

OWNERS

Bring the owners file to the same state as in `main`. The aim of this PR is mostly to trigger another run of the CI.

[release-5.6] Update owners file

---

config/dev-console.patch.json
web/console-extensions.json
web/src/pages/logs-detail-page.tsx
web/src/pages/logs-dev-page.tsx

Changes to handling the react router params in the console horizontal-nav extension, cause the `useParams` hook to return empty results.  Merging the url params that are passed as props to the component with the ones returned form `useParams` fixes the issue, and keeps backward compatibility with older console versions (4.12+).

LOG-4905: merge react router url params with props

---

web/cypress/integration/logs-dev-page.cy.ts
web/locales/en/plugin__logging-view-plugin.json
web/src/attribute-filters.tsx
web/src/components/logs-query-input.tsx
web/src/components/logs-toolbar.tsx
web/src/hooks/useLogs.ts
web/src/pages/logs-dev-page.tsx

Manual cherry pick of #174 and #179

[release-5.8] OU-319: Manual cherry pick allow dev console multiple namespaces

---

web/src/__tests__/logql-query.spec.ts
web/src/logql-query.ts

This PR fixes a bug related to parsing the line filter in a LogQL expression

LOG-5268: fix line filters parsing

---

web/src/attribute-filters.tsx
web/src/pages/logs-dev-page.tsx
web/src/pages/logs-page.tsx

This PR looks to ensure that pods which are no longer available are able to have their logs be selected as a filter. 
This does create a behavior change on the Admin > Logs filter, as before even if there were no logs for a pod it would still be displayed in the list, while now only pods which have logs will be displayed. I believe that this makes sense and will make our software easier to use, but if this isn't desired behavior, I can add in an array merge to make sure that the pods that haven't sent logs still show up to filter to.

LOG-5287: Update the Admin > Logs page to pull the available pod list from the Loki API

---

logging-view-plugin-resources.yml

Special thanks to @zhuje and @jgbernalp for this fix.
The logging-view-plugin-resources.yml was outdated, so this pr is to update it so users can run the plugin on the cluster without issues.

Fix logging-view-plugin-resources.yml

---

web/src/cancellable-fetch.ts

The `ConsolePlugin.Proxy.Spec` requires the CSRF value to be present in both the cookie and the header for POST requests. This PR applies the cookie value into the header on all outbound POST requests. 
As of now the only POST request is the single korrel8r API endpoint.  However, we are making this change to all possible POST requests for now to proactively prevent the header from being missed if either korrel8r or the logging proxies end up needing further POST requests in the future.

OU-456: Add CSRF header on POST requests to avoid proxy filter

---

web/src/hooks/useLogActionsExtension.tsx
web/src/korrel8r-client.ts
web/src/korrel8r.types.ts

This PR backports the korrel8r client so it can be used to get links from alerts to logs

[release-5.7] LOG-5032: backport korrel8r client to get links from alerts to logs

---

web/package-lock.json
web/package.json
web/src/__tests__/logql-query.spec.ts
web/src/logql-query.ts

Adds support for Loki 3.x pattern line filters `|>` and `!>` such us:
```
{ log_type="application" }  |> "I <_>"| json
```
and
```
{ log_type="application" }  !> "I <_>"| json
```
Follow up on testing of:
- https://github.com/observatorium/api/pull/723
Depends on:
- https://github.com/grafana/lezer-logql/pull/63

LOG-5761: Add support LogQL pattern line filters

---

hack/docker-compose/docker-compose.test.yml
hack/docker-compose/loki/loki-config.yml
web/cypress/fixtures/query-range-fixtures.ts
web/cypress/integration/logs-page.cy.ts
web/locales/en/plugin__logging-view-plugin.json
web/src/components/execute-volume-button.tsx
web/src/components/logs-metrics.tsx
web/src/components/logs-query-input.css
web/src/components/logs-query-input.tsx
web/src/components/logs-toolbar.tsx
web/src/hooks/useLogs.ts
web/src/logs.types.ts
web/src/loki-client.ts
web/src/pages/logs-detail-page.tsx
web/src/pages/logs-dev-page.tsx
web/src/pages/logs-page.tsx
web/src/test-ids.ts

Currently the logging-view-plugin does not have the ability for the user to view [the Loki Volume API](https://grafana.com/docs/loki/next/reference/loki-http-api/#query-log-volume). This PR is to address this by creating a graph within the logging-view-plugin to allow users to have a view of the volume of logs before they run a query.

OU-483: Add the Volume API to the Logging-View-Plugin

---

Dockerfile.ci
Dockerfile.dev
Makefile
go.mod
scripts/image.sh

This PR looks to add FIPS support to the logging-view-plugin. It updates the go version to 1.22, and uses recommended FIPS compliant images and tags. Due to some of the recommended images not being available publicly a Dockerfile.dev is added to the repo as a way to build and test images locally.

OU-446: Support FIPS

---

web/src/pages/logs-detail-page.tsx
web/src/pages/logs-dev-page.tsx
web/src/pages/logs-page.tsx

Currently, the refresh button in the logging-view-plugin doesn't follow PatternFly guidelines since it's a primary button which conflicts with the `Run Query` button. According to PatternFly, there can only be one primary button on a page. This PR is to address that.

Fix Refresh Button to Follow PatternFly Guidelines

---

web/mockModules/dummy.tsx
web/src/components/logs-table.tsx

The console codebase follows a specific service + port combination to forward low-permission users to retrieve prometheus results. Korrel8r isn't set up with regards to this, as it operates at a full cluster level, so this PR looks to remove links which won't work for low permission users.
Low Permission User:
Kubeadmin

COO-301: Prevent korrel8r link from showing when Non-Admin

---

README.md
cmd/plugin-backend.go
pkg/server/server.go

JIRA: https://issues.redhat.com/browse/OU-525
Based on changes from openshift/monitoring-plugin: https://github.com/openshift/monitoring-plugin/pull/186

OU-525: Reduce excess logs

---

Dockerfile
Dockerfile.dev
Dockerfile.konflux

This PR:
- Removes husky installation for containers
- Adds a non root user in konflux image
- Adds a licenses folder required for konflux checks
- Adds labels to the image

NO-JIRA: update konflux image

---

cmd/plugin-backend.go
pkg/server/server.go

https://issues.redhat.com/browse/OU-576
Based on modifications from monitoring-plugin: https://github.com/openshift/monitoring-plugin/pull/264
QE subtask:
https://issues.redhat.com/browse/OU-576
https://drive.google.com/file/d/15yfDqW4Nt_8IyN8BiX-lmhffeph-6Tln/view?usp=sharing
Figure 1. Video demo (~3 min). Shows TLS certificates being dynamically reloaded. Shows logging-view-plugin pod logs that describe the reason for reloading and shows new certificate present in a pod using openssl s_client.
/hold
For QE testing

OU-539: Dynamically Reload Certificates

---

.gitignore
Dockerfile.devspace
Makefile
README.md
charts/openshift-console-plugin/.helmignore
charts/openshift-console-plugin/Chart.yaml
charts/openshift-console-plugin/templates/_helpers.tpl
charts/openshift-console-plugin/templates/configmap.yaml
charts/openshift-console-plugin/templates/consoleplugin.yaml
charts/openshift-console-plugin/templates/deployment.yaml
charts/openshift-console-plugin/templates/patch-consoles-job.yaml
charts/openshift-console-plugin/templates/patcher-clusterrole.yaml
charts/openshift-console-plugin/templates/patcher-clusterrolebinding.yaml
charts/openshift-console-plugin/templates/patcher-serviceaccount.yaml
charts/openshift-console-plugin/templates/service.yaml
charts/openshift-console-plugin/templates/serviceaccount.yaml
charts/openshift-console-plugin/values.yaml
devspace-deployment.yaml
devspace.yaml
devspace_start.sh

This PR looks to add a better set of development environments. This is completed through the use of 2 actions:
1. Add a helm chart to deploy the logging-view-plugin
2. Add devspace commands `devspace dev` and `devspace purge` to sync a webpack dev server output up into the cluster.
More information can be found in the README doc.

NO-JIRA: Add devspace configuration

---

README.md

devspace use namespace openshift-cluster-observability-operator

NO-JIRA: README update example namespace used for `devspace use {NAMESPACE}` 

---

web/src/__tests__/parse-resource.spec.ts
web/src/components/logs-table.tsx
web/src/parse-resources.tsx

https://issues.redhat.com/browse/OU-676
Support stream labels from ViaQ (old data model) and OpenTelemetry (new data model) to display resource information in logging-view-plugin. 
| Resource Required                 | ViaQ Stream Label                       | OpenTelemetry Stream Label  |
|-----------------------------|---------------------------------|-------------------------------|
| Namespace                            | kubernetes_namespace_name   | k8s_namespace_name             |
| Pod Name                               | kubernetes_pod_name               | k8s_pod_name                          |
| Container Name                     | k8s_container_name                   | k8s_container_name                 |
**Acceptance Criteria**: Resource links still navigate to the correct …

OU-676: Use OTel fields for displaying resource information in Log Console

---

web/src/__tests__/parse-resource.spec.ts
web/src/components/logs-table.tsx
web/src/parse-resources.tsx

https://issues.redhat.com/browse/OU-677
Support stream labels from ViaQ (old data model) and OpenTelemetry (new data model) to display severity/level information in logging-view-plugin. 
| Resource Required                 | ViaQ Stream Label                       | OpenTelemetry Stream Label  |
|-----------------------------|---------------------------------|-------------------------------|
| Severity                                   | severity_text                                 | level        |
Logs tags with the correct CSS based on the severity level. See below for the CSS labels and the corresponding background colors. 
.lv-plugin__table__severity-critical::before {
background-color: var(--pf-v5-global--palette--purple-500);
}
.lv-plugin__table__severity-error::before { …

OU-677: Extract log information from OTel attributes

---

web/src/components/logs-metrics.tsx
web/src/components/value-formatter.ts

Humanize y axis ticks to avoid text overflow:

OU-670: fix: format y series ticks to avoid text overflow

---

pkg/server/server.go
web/cypress/integration/logs-dev-page.cy.ts
web/cypress/integration/logs-page.cy.ts
web/locales/en/plugin__logging-view-plugin.json
web/src/__tests__/attribute-filters.spec.ts
web/src/__tests__/loki-client-spec.ts
web/src/attribute-filters.tsx
web/src/backend-client.ts
web/src/cancellable-fetch.ts
web/src/components/alerts/logs-alerts-metrics.tsx
web/src/components/filters/attribute-filter.tsx
web/src/components/filters/attribute-value-data.tsx
web/src/components/logs-histogram.tsx
web/src/components/logs-query-input.tsx
web/src/components/logs-toolbar.tsx
web/src/components/schema-dropdown.tsx
web/src/getAlertingRules.ts
web/src/hooks/LogsConfigProvider.tsx
web/src/hooks/useLogs.ts
web/src/hooks/useURLState.ts
web/src/logs.types.ts
web/src/loki-client.ts
web/src/pages/logs-detail-page.tsx
web/src/pages/logs-dev-page.tsx
web/src/pages/logs-page.tsx
web/src/parse-resources.tsx
web/src/test-ids.ts
web/src/value-utils.ts

Fixes:
- [OU-731](https://issues.redhat.com/browse/OU-731)
- [OU-313](https://issues.redhat.com/browse/OU-313)
Notable changes:
- @zhuje added the parsing of new otel labels and attributes, and the schema dropdown
- Created a new useLogsConfig hook and provider to share the same config across components and hooks, pages are now wrapped with this provider
- Added the schema configuration to the backend plugin config
- Removed the logs_type matcher if there are other matchers: [OU-313](https://issues.redhat.com//browse/OU-313)
- As initial queries and attributes depend on the selected/configured schema, the useURLState hook now accepts initializer functions for these values
- When changing the schema the current query is updated to match the correct model labels
UX:
Added the schema …

OU-731: feat: add otel for quering support and plugin configuration
